[project]
name = "repl-nix-workflowwizard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.42.0",
    "requests>=2.32.3",
    "websocket>=0.2.1",
    "websocket-client>=1.8.0",
]
